---
- name: set fact desired fortios firmware local
  set_fact:
    desired_build: "{{ downgrade_path[current_version][current_build] }}"
    desired_major_version: "{{ downgrade_path[current_version][current_major_version] }}"

- name: Downgrade FortiOS firmware local to {{ desired_build }}
  fortios_system_firmware_upgrade:
    host:  "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vdom:  "{{ vdom }}"
    ssl_verify: "False"
    system_firmware:
      file_content: "base64"
      format_partition: "False"
      filename: "{{ firmware_path }}{{ device_type }}-v{{ desired_major_version }}-build{{ desired_build }}-FORTINET.out"
      source: "upload"
  register: fortios_system_firmware_upgrade_result

