---
- name: set fact desired fortios firmware for fortiguard
  set_fact:
    desired_build: "{{ansible_facts.network_resources.system_firmware_select.results.available.0.build}}"
    desired_id: "{{ansible_facts.network_resources.system_firmware_select.results.available.0.id}}"
    desired_version: "{{ansible_facts.network_resources.system_firmware_select.results.available.0.version}}"

- name: Upgrade FortiOS firmware fortiguard to {{ desired_version.msg }}
  fortios_system_firmware_upgrade:
    host:  "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vdom:  "{{ vdom }}"
    ssl_verify: "False"
    system_firmware:
      format_partition: "False"
      filename: "{{ desired_id.msg }}"
      source: "fortiguard"
  register: fortios_system_firmware_upgrade_result
  when: 
    - desired_build is defined
    - current_build is defined
    - desired_build > current_build
