---
- name: Get BGP info
  fortios_router_bgp_info:
    host:  "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    vdom:  "{{ bgp_vdom }}"
    ssl_verify: "False"
    bgp_info:
      scope: "vdom"
  register: fortios_router_bgp_info_result

